### ISSUE TITLE
Update to latest The Things Uno SDK

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/arduino-library#2]
This is an old fork of The Things Uno SDK. The current version, in `TheThingsNetwork/sdk/devices/TheThingsUno` is 0.15+ afaik, with downlink support.

**Comment by FokkeZB** [comment]
My mistake... used my local, out-dated version. I've updated it and renamed all use of `TheThingsUno` and `ttu` to `TheThingsNetwork` and `ttn`

**Comment by FokkeZB** [comment]
Aaaaand fixed the fix 😬

**Comment by johanstokking** [comment]
Thanks
