### ISSUE TITLE
Document API in detail

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/arduino-library#8]
The [README](https://github.com/TheThingsNetwork/arduino-library#api) lists the headers of the public API but it needs to be documented in detail.

**Comment by Nicolasdejean** [comment]
Can we do a small decription of every functions like that: 
void init(Stream& modemStream, Stream& debugStream);  /* Initialize The arduino device */
or do we create a whole part with a title "Function details" for example where we detail precisely every function(use of the function, use of arguments...)

**Comment by FokkeZB** [comment]
Done: https://www.thethingsnetwork.org/docs/arduino/#api-reference
